# Generated by Django 3.2.25 on 2024-05-21 13:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(help_text='Текст о компании', verbose_name='Описание компании')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заголовок', max_length=100, verbose_name='Наименование преимущества')),
                ('text', models.TextField(help_text='Описание', verbose_name='Описание преимущества')),
                ('image', models.ImageField(help_text='Загрузите иконку', upload_to='media/advantages/', verbose_name='Изображение преимущества')),
            ],
            options={
                'verbose_name': 'Наше преимущество',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='e-mail для связи c контактным лицом', max_length=254, verbose_name='e-mail для связи')),
                ('telephone', models.CharField(help_text='контактный телефон', max_length=15, verbose_name='контактный телефон')),
                ('adress', models.TextField(blank=True, help_text='почтовый адрес', verbose_name='адрес комапании')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DiameterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.IntegerField(default=None, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Условный диаметр колонны',
                'verbose_name_plural': 'Условный диаметр колонны',
            },
        ),
        migrations.CreateModel(
            name='DiameterOpenBorehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Диаметр открытого ствола',
                'verbose_name_plural': 'Диаметр открытого ствола',
            },
        ),
        migrations.CreateModel(
            name='DiameterShank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.IntegerField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Условный диаметр хвостовика',
                'verbose_name_plural': 'Условный диаметр хвостовика',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, help_text='Изображение для главной страницы', upload_to='media/website/')),
                ('about', models.TextField(help_text='Описание компании на гланой странице', verbose_name='Оисание краткое')),
                ('main_title', models.CharField(help_text='Заголовок и meta', max_length=250, verbose_name='Заголовок главной страницы')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование партнера', max_length=150, verbose_name='Название партера')),
                ('image', models.ImageField(blank=True, help_text='Логотип партнера', upload_to='media/website/')),
            ],
            options={
                'verbose_name': 'Наш партнёр',
                'verbose_name_plural': 'Наши партнёры',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Тип оборудования')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
                ('image', models.ImageField(help_text='Добавьте файл c изображением', upload_to='media/img/type/', verbose_name='Изображение')),
                ('inmgrp', models.BooleanField(default=False, verbose_name='Оборудование входит в комплект')),
                ('incalc', models.BooleanField(default=False, verbose_name='Включить в калькулятор')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('seo_description', models.CharField(max_length=160, verbose_name='Описание для поисковиков, <160 символов')),
                ('seo_keywords', models.CharField(max_length=300, verbose_name='ключевые слова через запятую <10')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование оборудования')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('image', models.ImageField(help_text='Добавьте файл c изображением', upload_to='media/img/product/', verbose_name='Изображение')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('slug', models.SlugField(max_length=300, verbose_name='URL')),
                ('fitting_outer_diameter', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, verbose_name='Наружный диаметр оснастки, мм')),
                ('fitting_inner_diameter', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, verbose_name='Внутренний диаметр оснастки')),
                ('fitting_length', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, verbose_name='Длина оснастки')),
                ('incalc', models.BooleanField(default=False, verbose_name='Включить в калькулятор')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('seo_description', models.CharField(max_length=160, verbose_name='Описание для поисковиков, <160 символов')),
                ('seo_keywords', models.CharField(max_length=300, verbose_name='ключевые слова через запятую <10')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('diameter_column', models.ManyToManyField(related_name='diameter_column', to='website.DiameterColumn', verbose_name='Условный диаметр колонны')),
                ('diameter_open_borehole', models.ManyToManyField(related_name='diameter_open_borehole', to='website.DiameterOpenBorehole', verbose_name='Диаметр открытого ствола')),
                ('diameter_shank', models.ManyToManyField(related_name='diameter_shank', to='website.DiameterShank', verbose_name='Условный диаметр хвостовика')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.type', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monetary_unit', models.CharField(max_length=5, verbose_name='Денежная единица')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
            options={
                'verbose_name': 'Стоимость продукции',
                'verbose_name_plural': 'Стоимость продукции',
            },
        ),
    ]
