# Generated by Django 3.2.25 on 2024-06-20 14:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, help_text='About company full descrintion', null=True, verbose_name='Descrteion company'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='name_en',
            field=models.CharField(blank=True, help_text='Title', max_length=100, null=True, verbose_name='Advantages title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='text_en',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description of advatages'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_en',
            field=models.TextField(blank=True, help_text='Short description on main page', null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_title_en',
            field=models.CharField(blank=True, help_text='Title and meta tag', max_length=250, null=True, verbose_name='Title of main page and meta tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.TextField(blank=True, help_text='Post adress', null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about',
            field=models.TextField(help_text='Описание компании на главной странице', verbose_name='Описание краткое'),
        ),
    ]
