# Generated by Django 3.2.25 on 2024-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240620_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='adress_en',
            field=models.TextField(blank=True, help_text='Post adress', null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.TextField(blank=True, help_text='почтовый адрес', null=True, verbose_name='адрес комапании'),
        ),
    ]
