# Generated by Django 3.2.25 on 2024-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
